/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Poker;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new Poker().compare("KH 4S 4C 6D 6H", "2S 4S 4D 6H 6S"));
    }
}
